### ISSUE TITLE
Empty passwords causes module to fail authentication

### ISSUE THREAD

**Issue by MajesticFalcon** [ansible-collections/community.routeros#11]
##### SUMMARY

When Mikrotiks come out of the box, they do not have a password. In order to do automatic provisioning, I need this module to be able to handle empty string passwords. The fix seems to be an adjustment to the call to paramiko.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.routeros.command

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sutley/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sutley/.local/lib/python3.6/site-packages/ansible
  executable location = /home/sutley/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]

```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu

##### STEPS TO REPRODUCE

1. Configure inventory for mikrotik host with a password = ""

```yaml
- hosts: CPE
  become: yes
  gather_facts: no
  become_method: enable
  connection: ansible.netcommon.network_cli
  environment:
    remote_tmp: /
  tasks:
    - name: Display resource statistics (routeros)
      community.network.routeros_command:
        commands: /system resource print
      register: routeros_resources
    - debug:
        var: routeros_resources
```

##### EXPECTED RESULTS

Output the resources

##### ACTUAL RESULTS

Depends on if you provide a empty string password or not. If you don't then you get auth failure, if you do you get no existing session
```paste below
sutley@netbox:/optimizing_cpes/ansible$ ansible-playbook -i netbox_inventory.yml ./routeros.yml -e "ansible_network_os=routeros ansible_password=" -vvv
ansible-playbook 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sutley/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sutley/.local/lib/python3.6/site-packages/ansible
  executable location = /home/sutley/.local/bin/ansible-playbook
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /optimizing_cpes/ansible/netbox_inventory.yml as it did not pass its verify_file() method
script declined parsing /optimizing_cpes/ansible/netbox_inventory.yml as it did not pass its verify_file() method
Fetching: https://172.16.100.56/api/dcim/sites/?limit=0
Fetching: https://172.16.100.56/api/dcim/regions/?limit=0
Fetching: https://172.16.100.56/api/tenancy/tenants/?limit=0
Fetching: https://172.16.100.56/api/dcim/racks/?limit=0
Fetching: https://172.16.100.56/api/dcim/device-roles/?limit=0
Fetching: https://172.16.100.56/api/dcim/platforms/?limit=0
Fetching: https://172.16.100.56/api/dcim/device-types/?limit=0
Fetching: https://172.16.100.56/api/dcim/manufacturers/?limit=0
Fetching: https://172.16.100.56/api/dcim/devices/?limit=0
Fetching: https://172.16.100.56/api/virtualization/virtual-machines/?limit=0
Parsed /optimizing_cpes/ansible/netbox_inventory.yml inventory source with auto plugin

PLAYBOOK: routeros.yml *************************************************************************************************************
1 plays in ./routeros.yml

PLAY [AUTOCPE] *********************************************************************************************************************
META: ran handlers

TASK [Display resource statistics (routeros)] **************************************************************************************
task path: /optimizing_cpes/ansible/routeros.yml:9
<192.168.255.3> ESTABLISH LOCAL CONNECTION FOR USER: sutley
<192.168.255.3> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe `"&& mkdir "` echo /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe/ansible-tmp-1604963164.6908667-9998-224365925208779 `" && echo ansible-tmp-1604963164.6908667-9998-224365925208779="` echo /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe/ansible-tmp-1604963164.6908667-9998-224365925208779 `" ) && sleep 0'
<AUTOCPE> Attempting python interpreter discovery
<192.168.255.3> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.168.255.3> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/sutley/.ansible/collections/ansible_collections/community/network/plugins/modules/routeros_command.py
<192.168.255.3> PUT /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe/tmp_tyn5d4x TO /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe/ansible-tmp-1604963164.6908667-9998-224365925208779/AnsiballZ_routeros_command.py
<192.168.255.3> EXEC /bin/sh -c 'chmod u+x /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe/ansible-tmp-1604963164.6908667-9998-224365925208779/ /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe/ansible-tmp-1604963164.6908667-9998-224365925208779/AnsiballZ_routeros_command.py && sleep 0'
<192.168.255.3> EXEC /bin/sh -c 'remote_tmp=/ /usr/bin/python /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe/ansible-tmp-1604963164.6908667-9998-224365925208779/AnsiballZ_routeros_command.py && sleep 0'
<192.168.255.3> EXEC /bin/sh -c 'rm -f -r /home/sutley/.ansible/tmp/ansible-local-99849lt4dzhe/ansible-tmp-1604963164.6908667-9998-224365925208779/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_community.network.routeros_command_payload_1eNpxa/ansible_community.network.routeros_command_payload.zip/ansible_collections/community/network/plugins/module_utils/network/routeros/routeros.py", line 74, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/tmp/ansible_community.network.routeros_command_payload_1eNpxa/ansible_community.network.routeros_command_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host AUTOCPE should use /usr/bin/python3, but is using /usr/bin/python for
backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python
for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This
feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [AUTOCPE]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "/system resource print"
            ],
            "interval": 1,
            "match": "all",
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "No existing session"
}

```

**Comment by MajesticFalcon** [comment]
https://github.com/paramiko/paramiko/issues/890

**Comment by felixfontein** [comment]
I'm not sure there's a way for us to do anything about this.

You could try setting `transport = ssh` in your ansible.cfg to use OpenSSH (or whatever your local `ssh` binary is) instead of paramiko. Alternatively, you can use the `ANSIBLE_TRANSPORT` env variable to try it out quickly: `ANSIBLE_TRANSPORT=ssh ansible-playbook ...`. If this works, we could document this as a workaround.

**Comment by NikolayDachev** [comment]
https://github.com/paramiko/paramiko/issues/890#issuecomment-575987988 

I think we should not put exceptions or other code changes on this stage for issues related to paramiko lib which probably will be fixed soon 

@MajesticFalcon can you try what @felixfontein suggest as temporary solution until paramiko is fixed (look like will be soon )?

**Comment by renatoalmeidaoliveira** [comment]
@NikolayDachev maybe some exception handling for a pretty output. Because netmiko could have other bugs, now or in the future.

**Comment by felixfontein** [comment]
I'm not sure there's anything we can actually do here. I guess this needs to be fixed in ansible/ansible (https://github.com/ansible/ansible/), since the paramiko connection plugin is part of it. I'm not familiar enough with it to know where this really needs to happen though.

**Comment by MajesticFalcon** [comment]
I will give it a try and let yall know.

**Comment by MajesticFalcon** [comment]
@NikolayDachev @felixfontein 
I tried a couple different methods, none work. Is the routeros package hardcoded to use paramiko? I tried the following:
Setting the environment variable
Setting the config file variable
Setting the runtime variable (-c ssh)

All gave the same error as the paramiko. This gave me the suspicion that it wasn't working. I uninstalled paramiko and sure enough, I cannot get the module to accept the ssh parameter.

`sutley@netbox:/optimizing_cpes/ansible$ ANSIBLE_TRANSPORT=ssh ansible-playbook -i netbox_inventory.yml ./routeros.yml -c ssh -e "ansible_network_os=routeros ansible_password=''" -vvvv
ansible-playbook 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sutley/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sutley/.local/lib/python3.6/site-packages/ansible
  executable location = /home/sutley/.local/bin/ansible-playbook
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /optimizing_cpes/ansible/netbox_inventory.yml as it did not pass its verify_file() method
script declined parsing /optimizing_cpes/ansible/netbox_inventory.yml as it did not pass its verify_file() method
Fetching: https://172.16.100.56/api/dcim/sites/?limit=0
Fetching: https://172.16.100.56/api/dcim/regions/?limit=0
Fetching: https://172.16.100.56/api/tenancy/tenants/?limit=0
Fetching: https://172.16.100.56/api/dcim/racks/?limit=0
Fetching: https://172.16.100.56/api/dcim/device-roles/?limit=0
Fetching: https://172.16.100.56/api/dcim/platforms/?limit=0
Fetching: https://172.16.100.56/api/dcim/device-types/?limit=0
Fetching: https://172.16.100.56/api/dcim/manufacturers/?limit=0
Fetching: https://172.16.100.56/api/dcim/devices/?limit=0
Fetching: https://172.16.100.56/api/virtualization/virtual-machines/?limit=0
Parsed /optimizing_cpes/ansible/netbox_inventory.yml inventory source with auto plugin
Loading callback plugin default of type stdout, v2.0 from /home/sutley/.local/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: routeros.yml *************************************************************************************************************
Positional arguments: ./routeros.yml
verbosity: 4
connection: ssh
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/optimizing_cpes/ansible/netbox_inventory.yml',)
extra_vars: ("ansible_network_os=routeros ansible_password=''",)
forks: 5
1 plays in ./routeros.yml

PLAY [AUTOCPE] *********************************************************************************************************************
META: ran handlers

TASK [Display resource statistics (routeros)] **************************************************************************************
task path: /optimizing_cpes/ansible/routeros.yml:9
<192.168.255.3> attempting to start connection
<192.168.255.3> using connection plugin ansible.netcommon.network_cli
<192.168.255.3> local domain socket does not exist, starting it
<192.168.255.3> control socket path is /home/sutley/.ansible/pc/3489c23219
<192.168.255.3> local domain socket listeners started successfully
<192.168.255.3> loaded cliconf plugin routeros from path /home/sutley/.local/lib/python3.6/site-packages/ansible/plugins/cliconf/routeros.py for network_os routeros
<192.168.255.3>
<192.168.255.3> local domain socket path is /home/sutley/.ansible/pc/3489c23219
<192.168.255.3> ESTABLISH LOCAL CONNECTION FOR USER: sutley
<192.168.255.3> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n `"&& mkdir "` echo /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n/ansible-tmp-1605418412.486874-26603-126011380778771 `" && echo ansible-tmp-1605418412.486874-26603-126011380778771="` echo /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n/ansible-tmp-1605418412.486874-26603-126011380778771 `" ) && sleep 0'
<AUTOCPE> Attempting python interpreter discovery
<192.168.255.3> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.168.255.3> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/sutley/.ansible/collections/ansible_collections/community/network/plugins/modules/routeros_command.py
<192.168.255.3> PUT /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n/tmpw2227x1v TO /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n/ansible-tmp-1605418412.486874-26603-126011380778771/AnsiballZ_routeros_command.py
<192.168.255.3> EXEC /bin/sh -c 'chmod u+x /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n/ansible-tmp-1605418412.486874-26603-126011380778771/ /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n/ansible-tmp-1605418412.486874-26603-126011380778771/AnsiballZ_routeros_command.py && sleep 0'
<192.168.255.3> EXEC /bin/sh -c 'remote_tmp=/ /usr/bin/python /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n/ansible-tmp-1605418412.486874-26603-126011380778771/AnsiballZ_routeros_command.py && sleep 0'
<192.168.255.3> EXEC /bin/sh -c 'rm -f -r /home/sutley/.ansible/tmp/ansible-local-26585iv4alp4n/ansible-tmp-1605418412.486874-26603-126011380778771/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_community.network.routeros_command_payload_N8hbha/ansible_community.network.routeros_command_payload.zip/ansible_collections/community/network/plugins/module_utils/network/routeros/routeros.py", line 74, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
  File "/tmp/ansible_community.network.routeros_command_payload_N8hbha/ansible_community.network.routeros_command_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host AUTOCPE should use /usr/bin/python3, but is using /usr/bin/python for
backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python
for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This
feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [AUTOCPE]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "/system resource print"
            ],
            "interval": 1,
            "match": "all",
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "paramiko is not installed: No module named 'paramiko'"
}

PLAY RECAP *************************************************************************************************************************
AUTOCPE                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

`

**Comment by MajesticFalcon** [comment]
Actually, if I remove connection setting in the playbook, I get the following error:

```
sutley@netbox:/optimizing_cpes/ansible$ ANSIBLE_TRANSPORT=ssh ansible-playbook -i netbox_inventory.yml ./routeros.yml -c ssh -e "ansible_network_os=routeros ansible_password=''" -vvvv
ansible-playbook 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sutley/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sutley/.local/lib/python3.6/site-packages/ansible
  executable location = /home/sutley/.local/bin/ansible-playbook
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /optimizing_cpes/ansible/netbox_inventory.yml as it did not pass its verify_file() method
script declined parsing /optimizing_cpes/ansible/netbox_inventory.yml as it did not pass its verify_file() method
Fetching: https://172.16.100.56/api/dcim/sites/?limit=0
Fetching: https://172.16.100.56/api/dcim/regions/?limit=0
Fetching: https://172.16.100.56/api/tenancy/tenants/?limit=0
Fetching: https://172.16.100.56/api/dcim/racks/?limit=0
Fetching: https://172.16.100.56/api/dcim/device-roles/?limit=0
Fetching: https://172.16.100.56/api/dcim/platforms/?limit=0
Fetching: https://172.16.100.56/api/dcim/device-types/?limit=0
Fetching: https://172.16.100.56/api/dcim/manufacturers/?limit=0
Fetching: https://172.16.100.56/api/dcim/devices/?limit=0
Fetching: https://172.16.100.56/api/virtualization/virtual-machines/?limit=0
Parsed /optimizing_cpes/ansible/netbox_inventory.yml inventory source with auto plugin
Loading callback plugin default of type stdout, v2.0 from /home/sutley/.local/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: routeros.yml *************************************************************************************************************
Positional arguments: ./routeros.yml
verbosity: 4
connection: ssh
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/optimizing_cpes/ansible/netbox_inventory.yml',)
extra_vars: ("ansible_network_os=routeros ansible_password=''",)
forks: 5
1 plays in ./routeros.yml

PLAY [AUTOCPE] *********************************************************************************************************************
META: ran handlers

TASK [Display resource statistics (routeros)] **************************************************************************************
task path: /optimizing_cpes/ansible/routeros.yml:7
<192.168.255.3> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.255.3> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/sutley/.ansible/cp/0cf369f6c5 192.168.255.3 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.255.3> (1, b'syntax error (line 1 column 5)\n', b'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /home/sutley/.ssh/config\r\ndebug1: /home/sutley/.ssh/config line 4: Applying options for 192.168.255.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26824\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
<192.168.255.3> Failed to connect to the host via ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /home/sutley/.ssh/config
debug1: /home/sutley/.ssh/config line 4: Applying options for 192.168.255.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 26824
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
<192.168.255.3> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.255.3> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/sutley/.ansible/cp/0cf369f6c5 192.168.255.3 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo syntax error (line 1 column 5)/.ansible/tmp `"&& mkdir "` echo syntax error (line 1 column 5)/.ansible/tmp/ansible-tmp-1605418857.2901263-26872-120856536815145 `" && echo ansible-tmp-1605418857.2901263-26872-120856536815145="` echo syntax error (line 1 column 5)/.ansible/tmp/ansible-tmp-1605418857.2901263-26872-120856536815145 `" ) && sleep 0'"'"''
<192.168.255.3> (1, b'syntax error (line 1 column 5)\n', b'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /home/sutley/.ssh/config\r\ndebug1: /home/sutley/.ssh/config line 4: Applying options for 192.168.255.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26824\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
<192.168.255.3> Failed to connect to the host via ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /home/sutley/.ssh/config
debug1: /home/sutley/.ssh/config line 4: Applying options for 192.168.255.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 26824
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
fatal: [AUTOCPE]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo syntax error (line 1 column 5)/.ansible/tmp `\"&& mkdir \"` echo syntax error (line 1 column 5)/.ansible/tmp/ansible-tmp-1605418857.2901263-26872-120856536815145 `\" && echo ansible-tmp-1605418857.2901263-26872-120856536815145=\"` echo syntax error (line 1 column 5)/.ansible/tmp/ansible-tmp-1605418857.2901263-26872-120856536815145 `\" ), exited with result 1, stdout output: syntax error (line 1 column 5)\n, stderr output: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /home/sutley/.ssh/config\r\ndebug1: /home/sutley/.ssh/config line 4: Applying options for 192.168.255.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26824\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n",
    "unreachable": true
}

PLAY RECAP *************************************************************************************************************************
AUTOCPE                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0


```

**Comment by NikolayDachev** [comment]
Can you try to delegate to localhost in your playbook

**Comment by felixfontein** [comment]
The connection setting is needed. It could also be that the network_cli connection (it's in this collection: https://github.com/ansible-collections/ansible.netcommon) only works with paramiko. I just looked up the docs for network_cli, you have to change this configuration: https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/network_cli_connection.html#parameter-ssh_type

**Comment by MajesticFalcon** [comment]
Thank you. Ill try it out again and let you know!

**Comment by MajesticFalcon** [comment]
@felixfontein 
That worked! Thank you.
I was hoping that setting would allow me to now SFTP/SCP files onto the Mikrotik, but it doesn't. Net_put errors out about
`  fatal: [AUTOCPE]: FAILED! => {"changed": false, "destination": "test.rsc", "msg": "Exception received: 'pylibsshext.session.Session' object has no attribute 'get_transport'"}`
I suppose this means net_put doesn't support using libssh.

**Comment by NikolayDachev** [comment]
@heuels @felixfontein ,  I think we should close this issue if something else is not related to the module it self

**Comment by felixfontein** [comment]
I agree. `net_put` is also not part of this collection, so there's really nothing we can do here. @MajesticFalcon please report the `net_put` problem in the collection it belongs to: https://github.com/ansible-collections/ansible.netcommon

**Comment by NikolayDachev** [comment]
Closing the issue since look like is not directly related to community.routeros

**Comment by mplattner** [comment]
I know this has been closed, but does anyone know if there is a solution by now that allows to set the password of a fresh Mikrotik CHR that has no password set yet? Thanks!

**Comment by vchrizz** [comment]
I struggled with that issue too using paramiko. Since I installed ansible-pylibssh via pip it finally works.

@mplattner Here a playbook to change the empty admin-pw:
```
- name: RouterOS - change admin password
  hosts: routeros
  vars:
    - ansible_connection: ansible.netcommon.network_cli
    - ansible_network_os: community.network.routeros
# add +cet512w to username to tell RouterOS to not wrap before 512 characters in a line. 
# details see: https://github.com/ansible-collections/community.routeros/issues/6
    - ansible_user: "admin+cet512w"
#    - ansible_password: ""
  tasks:
    - name: change password
      community.network.routeros_command:
        commands:
          - /user/set admin password=MyN3wPa55w0rd!
      register: routeros_cmd
      when: ansible_network_os == 'community.network.routeros'
      failed_when: routeros_cmd.stdout is defined and routeros_cmd.stdout|first != ""
    - name: Output of command
      debug:
        msg: "output: {{ routeros_cmd }}"
```

**Comment by mplattner** [comment]
Cool, thanks @vchrizz, I'll test this next time I'm changing my terraform scripts for Mikrotik 👍
