### ISSUE TITLE
Support for automatic dependency assembly (librouteros), when building a docker container execution environment for AWX

### ISSUE THREAD

**Issue by yurenkov** [ansible-collections/community.routeros#113]
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
Support for automatic dependency assembly (librouteros), when building a docker container execution environment for AWX. Look https://github.com/ansible/awx-ee/tree/0.6.0 and https://ansible-builder.readthedocs.io/en/latest/collection_metadata.html
To do this, add a file to the root of the project requirements.txt with the contents of librouteros. That will be enough.

```yaml

```

**Comment by felixfontein** [comment]
What exactly seems to be missing? EE support should already work, see https://github.com/ansible-collections/community.routeros/blob/main/meta/execution-environment.yml and #83.

**Comment by yurenkov** [comment]
Oh, sorry. I used release 2.0.0.
Now I checked with release 2.3.0. Everything is fine.
