### ISSUE TITLE
Support new paths

### ISSUE THREAD

**Issue by izzzhoga** [ansible-collections/community.routeros#114]
##### SUMMARY
Good day! I use your module to automate the configuration of my Mikrotik. There was a need to configure the following paths in the configuration:
/system logging; /system logging action

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.routeros.api_modify module – Modify data at paths with API

##### ADDITIONAL INFORMATION
Here is an example of the command I need to execute on my Mikrotik:
/system logging action add email-start-tls=yes email-to={{ smtp_mail_to_addr }} name={{ smtp_logging_action_name }} target=email
/system logging add action={{ smtp_logging_action_name }} topics=critical
/system logging add action={{ smtp_logging_action_name }} topics=error
/system logging add action={{ smtp_logging_action_name }} topics=warning

I'm sorry if there are errors in the text!

**Comment by felixfontein** [comment]
I know too little about these paths to feel confident enough to implement them. If someone wants to try, feel free!

**Comment by therfert** [comment]
The failed checks were caused by a network issue on github. I don't have permissions to re-run them.

**Comment by izzzhoga** [comment]
Good afternoon! Thank you so much for adding new paths!
I haven't had time to try them out yet, but I will definitely do it soon

**Comment by felixfontein** [comment]
@izzzhoga all the new changes are in the latest release (2.4.0) from yesterday, so you can try them out without having to install this collection from source or something like that.
