### ISSUE TITLE
api_modify unsupported keys

### ISSUE THREAD

**Issue by snookit** [ansible-collections/community.routeros#115]
Hello there, 
I've started to work with this collection to configure routeros hardware, first of all thanks for this great piece of software it's a real pleasure working with it !

##### SUMMARY
I've encountered some keys unsupported by api_modify :
```
- name: ip firewall filter
  community.routeros.api_modify:
    path: ip firewall filter
    data: 
      "{{ firewall_filters }}"

loop item :
        {
            "action": "fasttrack-connection",
            "chain": "forward",
            "connection-state": "established,related",
            "hw-offload": true,
        },

result:
TASK [mikrotik : ip firewall filter] 
FAILED! => {"changed": false, "msg": "Unknown key \"hw-offload\" at index 1."}
```

Same here : 
```
- name: interface ethernet
  community.routeros.api_modify:
    path: interface ethernet
    data: 
      "{{ interfaces_ethernet }}"

loop item: 
        {
            "default-name": "ether5",
            "name": "ether5-test",
            "poe-out": "auto-on"
        },

result:
TASK [mikrotik : interface ethernet] 
FAILED! => {"changed": false, "msg": "Unknown key \"poe-out\" for default-name=\"ether5\"."}
```
I don't use it but I noticed poe-priority key is also missing for "interface ethernet" path

I've added these keys in my local plugins/module_utils/_api_data.py file and these tasks are running happily

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.routeros.api_modify

##### ANSIBLE VERSION
```
ansible [core 2.12.9]
  python version = 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
Collection         Version
------------------ -------
community.routeros 2.3.0
```

##### OS / ENVIRONMENT
Mikrotik ROS 7.5 (stable)

**Comment by felixfontein** [comment]
I created #121 for this. I saw some more missing fields in `interface ethernet`. About `hw-offload`: that doesn't seem to exist on my router, maybe it needs ROS7 or a better model. In any case I also added it so that folks who have it can use it.
