### ISSUE TITLE
[api_facts] Add "gather_subset: config"

### ISSUE THREAD

**Issue by izzzhoga** [ansible-collections/community.routeros#147]
##### SUMMARY
Hello! It's me, again :)
I wanted to make an analogue of the Mikrotik command (/export), not a specific path, but the entire configuration.
I tried to implement this using the community.routeros.api, but it did not lead to success.

```
- name: Collect all config from the device
  community.routeros.api:
    path: /
    cmd: export
  register: result

- name: debug result
  debug:
    msg: "{{ result }}"
```
```
TASK [1DEV/mkt : Collect all config from the device]****************************************************************
ok: [Mikrotik]

TASK [1DEV/mkt : debug result]**************************************************************************************
ok: [Mikrotik] => {
    "msg": {
        "changed": false,
        "failed": false,
        "msg": []
    }
}
```

Next, I tried to use community.routeros.api_facts, but the gather_subset parameter does not have the "config" value, as it was implemented in the similar ssh module community.routeros.facts.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.routeros.api_facts module – Collect facts from remote devices running MikroTik RouterOS using the API

##### ADDITIONAL INFORMATION
I would like to get /export with Mikrotik the following task

```
- name: Collect all config from the device
  community.routeros.api_facts:
    gather_subset: config
  register: result
```

And get approximately the following result, as implemented in community.routeros.facts

```
"msg": {
        "ansible_net_config": "# jan/19/2023 10:04:08 by RouterOS 6.46.5\n# software id = \n ****************",
        "ansible_net_config_nonverbose": "# RouterOS 6.46.5\n# software id = \n ****************"
}
```

**Comment by felixfontein** [comment]
> Next, I tried to use community.routeros.api_facts, but the gather_subset parameter does not have the "config" value, as it was implemented in the similar ssh module community.routeros.facts.

That's because there is no simple API equivalent to the CLI `/export`. I noticed that while implementing api_facts and decided to skip it until someone figures out how to do it in a nice way :)

I think you can only export to a file on the router via the API, and then you have to fetch that file. Which isn't very nice.

Anyway, if you know how to achieve this in a nice way using the API, I'll happily implement it...
