### ISSUE TITLE
api_modify: Suspected strange beheviour of the `match_entries` and `essentially_same_weight` methods

### ISSUE THREAD

**Issue by phox142** [ansible-collections/community.routeros#152]
Hello,
Maybe I am wrong but I find the behaviour of the [match_entries](https://github.com/ansible-collections/community.routeros/blob/f38b01d7bbc19e1c0fd2a8c90d948f34e5e1e9ba/plugins/modules/api_modify.py#L499) and [essentially_same_weight](https://github.com/ansible-collections/community.routeros/blob/f38b01d7bbc19e1c0fd2a8c90d948f34e5e1e9ba/plugins/modules/api_modify.py#L410) methods strange.

### Context:
I have a set of RouterOS devices and I'm trying to manage a set of default firewall filter rules for those devices.
As the requirement for those devices may vary it's required to be able to add some custom rules manually (managed by local admin)

### Problem:
As explained in the Context I can enabled "handle_absent_entries=remove"  for those firewall filters as it will remove all the custom rules.

So in the method match_entries it falls in the `else` which uses the `essentially_same_weight` method.

``` python
def match_entries(new_entries, old_entries, path_info, module):
    matching_old_entries = [None for entry in new_entries]
    old_entries = list(old_entries)
    matches = []
    handle_absent_entries = module.params['handle_absent_entries']
    if handle_absent_entries == 'remove':
        for new_index, (unused, new_entry) in enumerate(new_entries):
            for old_index, (unused, old_entry) in enumerate(old_entries):
                modifications, unused = find_modifications(old_entry, new_entry, path_info, module, return_none_instead_of_fail=True)
                if modifications is not None:
                    matches.append((new_index, old_index, len(modifications)))
    else:
        for new_index, (unused, new_entry) in enumerate(new_entries):
            for old_index, (unused, old_entry) in enumerate(old_entries):
                weight = essentially_same_weight(old_entry, new_entry, path_info, module)
                if weight is not None:
                    matches.append((new_index, old_index, weight))
    matches.sort(key=lambda entry: entry[2])
    for new_index, old_index, rating in matches:
        if matching_old_entries[new_index] is not None or old_entries[old_index] is None:
            continue
        matching_old_entries[new_index], old_entries[old_index] = old_entries[old_index], None
    unmatched_old_entries = [index_entry for index_entry in old_entries if index_entry is not None]
    return matching_old_entries, unmatched_old_entries
```
My problems are the following one :
#### when adding a new "*field*"
The method `essentially_same_weight` return *None* and the method `match_entries` put it in the `unmatched_old_entries` collection which cause the creation of a new entry (firewall filter row)
#### when removing a "*field*"
If `handle_entries_content` is set to *ignore* this field will be ignored and remains in the router configuration
If `handle_entries_content` is set to something else than *ignore* then a new entry (firewall filter row) because the method return *None* as for the 'adding a new field' case.

``` python
def essentially_same_weight(old_entry, new_entry, path_info, module):
    for k, v in new_entry.items():
        if k == '.id':
            continue
        disabled_k = None
        if k.startswith('!'):
            disabled_k = k[1:]
        elif v is None or v == path_info.fields[k].remove_value:
            disabled_k = k
        if disabled_k is not None:
            if disabled_k in old_entry:
                return None
            continue
        if k not in old_entry and path_info.fields[k].default == v:
            continue
        if k not in old_entry or old_entry[k] != v:
            return None
    handle_entries_content = module.params['handle_entries_content']
    weight = 0
    for k in old_entry:
        if k == '.id' or k in new_entry or ('!%s' % k) in new_entry or k not in path_info.fields:
            continue
        field_info = path_info.fields[k]
        if field_info.default is not None and field_info.default == old_entry[k]:
            continue
        if handle_entries_content != 'ignore':
            return None
        else:
            weight += 1
    return weight
```

Am I doing something wrong?

Thanks for you support.

**Comment by felixfontein** [comment]
This behavior is intended. Without `handle_absent_entries=remove` the module has no idea which entry should replace another one.

**Comment by phox142** [comment]
> This behavior is intended. Without `handle_absent_entries=remove` the module has no idea which entry should replace another one.

In that case, I don't see the goal of the method `essentially_same_weight` 

Should it be possible that the handle_absent_entries=remove works on a subset based on [`stratify_keys`](https://github.com/ansible-collections/community.routeros/blob/f38b01d7bbc19e1c0fd2a8c90d948f34e5e1e9ba/plugins/module_utils/_api_data.py#L1420)

**Comment by felixfontein** [comment]
> > This behavior is intended. Without `handle_absent_entries=remove` the module has no idea which entry should replace another one.
> 
> In that case, I don't see the goal of the method `essentially_same_weight`

If `handle_absent_entries=ignore` and `handle_entries_content=ignore`, it tries to match entries that you do not want to modify as close as possible. The weight it returns says how much information the entry contains that wasn't specified by the user, and then `match_entries` uses this weight to create a matching of old and new entries by minimizing this weight.

> Should it be possible that the handle_absent_entries=remove works on a subset based on [`stratify_keys`](https://github.com/ansible-collections/community.routeros/blob/f38b01d7bbc19e1c0fd2a8c90d948f34e5e1e9ba/plugins/module_utils/_api_data.py#L1420)

Right now it is not possible.

**Comment by phox142** [comment]
Thanks for the info
