### ISSUE TITLE
Every run of a playbook shows  bunch of  tasks with state changed, but vars are same. is it designed without idempotency?

### ISSUE THREAD

**Issue by satperm** [ansible-collections/community.routeros#178]
I's not bug report, it's question about idempotency, of module community.routeros.command

i have a playbook:

---
- name: Full configuration of mikrotik routers
  hosts: _routers
  gather_facts: false
  tasks: 
    - name: Fill full config to the router
      community.routeros.command:
        commands: "{{ item }}"
      with_items: "{{config_lines}}"
      
   vars are static, but every run shows me that something was changed ( without real change). 
   i hope to see green ok status when running playbook with same unchanged variables.
   
  Can anyone clarify me my doubts please?

**Comment by felixfontein** [comment]
The command module executes a command and always returnes `changed=true`, similar to ansible.builtin.command. If you want it to return `changed=false`, you need to use `changed_when` (https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_error_handling.html#defining-changed). The module doesn't know anything about the commands you run and has no idea whether they trigger a change or not.

**Comment by satperm** [comment]
Thanks for the fast answer, no it's clear.
