### ISSUE TITLE
DNS DoH settings are not supported

### ISSUE THREAD

**Issue by radokristof** [ansible-collections/community.routeros#230]
Dear all!

The following DoH DNS options are not supported (by API modify module):
          doh-max-concurrent-queries
          doh-max-server-connections
          doh-timeout

**Comment by derdeagle** [comment]
@radokristof I'd like to take care of this. Just to be sure you mean that your mentioned options are only missing in the `/ip dns` path, don't you?

**Comment by radokristof** [comment]
Yes, correct it is not available in that path.
