### ISSUE TITLE
Add support for ip firewall address-lists path

### ISSUE THREAD

**Issue by radokristof** [ansible-collections/community.routeros#255]
Related to this request/commit: https://github.com/ansible-collections/community.routeros/issues/236

Would be great if we could even add address-lists as well via API

**Comment by derdeagle** [comment]
@radokristof Would you mind elaborating a bit more on what you need? Managing (so also adding) entries in the `ip firewall address-list` path is already possible. Am I missing something?

**Comment by radokristof** [comment]
@derdeagle Sorry you are right. It was just a typo on my end, but from the error I received I assumed it is missing :)

**Comment by derdeagle** [comment]
Great, no problem!
