### ISSUE TITLE
Fail task on !trap from API

### ISSUE THREAD

**Issue by jplitza** [ansible-collections/community.routeros#32]
##### SUMMARY

It is currently impossible to catch a failed API command, because the TrapError from librouteros is specifically excluded from failing the module. (And also because the `errors` method incorrectly compares to `"False"` (string) instead of `False` (boolean))

IMO this is the sole advantage of the API over the CLI: That it communicates what is an error in a meaningful way.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.routeros.api

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by heuels** [comment]
cc @NikolayDachev

**Comment by NikolayDachev** [comment]
> cc @NikolayDachev 

Thanks, will check this days

**Comment by felixfontein** [comment]
> IMO this is the sole advantage of the API over the CLI: That it communicates what is an error in a meaningful way.

Another big advantage is that you don't have to handle funky CLI problems like #31 :)

**Comment by NikolayDachev** [comment]
hey sorry I don't have physicals time to check this however can you please add example .. will help a lot

**Comment by felixfontein** [comment]
I've started a fix in #39 btw.

**Comment by felixfontein** [comment]
I think this is fixed by #39.
