### ISSUE TITLE
Task status failed when element is already exist on the Tik

### ISSUE THREAD

**Issue by baragoon** [ansible-collections/community.routeros#330]
##### SUMMARY
Hi,
Please advise me how to use your module like with linux box.
For example, if I do "assign ip address to some interface" on linux, task in the playbook will add this IP to the corresponding interface at the first playbook run and task will be marked as "changed". When I run this playbook again - task will be "OK".
With your module I'm trying to do the same with this task:

```
- name: Add example - ip address
  community.routeros.api:
    path: "ip address"
    add: "address=192.168.255.10/24 interface=bridge1"

```
First run is fine, address is added to the bridge1 and task is "changed"

```
TASK [Add example - ip address] ****************************************************************************************************************************************************************************
changed: [localhost]

```
But next run is failed, because address is already assigned on bridge1.

```
TASK [Add example - ip address] ****************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": ["failure: already have such address"]}

```
Expected to see "OK" for this task because IP is already there and no modification made.

I would like to describe my routers configuration in the single playbook/role and if I need to add something - add this to playbook and run. But instead of successful playbook run I'll get FAILED for the elements which are already defined.

Looks like I'm doing something wrong...
Thank you.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
community.routeros.api

##### ANSIBLE VERSION

```
ansible [core 2.17.5]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

**Comment by felixfontein** [comment]
The `community.routeros.api` module is for making changes that cannot be made with the other `community.routeros.api_*` modules. You should prefer the other modules over the `community.routeros.api` module, for example the `community.routeros.api_modify` module.
