### ISSUE TITLE
Add ~ option to routeros.api query parameter

### ISSUE THREAD

**Issue by TafkaMax** [ansible-collections/community.routeros#56]
##### SUMMARY
Add ~ option to routeros.api query parameter

https://docs.ansible.com/ansible/latest/collections/community/routeros/api_module.html#ansible-collections-community-routeros-api-module

The current documenation says: "WHERE valid operators are ==, !=, >, <."

But I would like to gather information from files using CONTAINS (~) operator.

e.g /file print where contents~"blaah"

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Update the already existing module.

##### ADDITIONAL INFORMATION

I want to search if a ssh pubkey file is present in the system. Ofcourse I could delete the previous one, but I would like to check its contents, and searching the contents with the full == operator is not viable. Also the mikrotik search seems to "brake" when it encounters a weird character.

```
[root@blaah] > /file print where contents~"ssh-rsa blaah+n"
 # NAME                                                                                                                        TYPE                                                                                                                             SIZE CREATION-TIME       
[root@blaah] > /file print where contents~"ssh-rsa blaah+" 
 # NAME                                                                                                                        TYPE                                                                                                                             SIZE CREATION-TIME       
 0 flash/blaah.pub                                                                                                          ssh key                                                                                                                           739 nov/01/2021 12:26:50

```

As you can see if I add anything after the + the search will break, even though the next letter is correct. Something to keep in mind.

**Comment by felixfontein** [comment]
Please note that `~` is not contains, but POSIX regular expression match. In regular expressions, `+` has a special meaning. This is probably why it doesn't work as expected in your use case.

**Comment by felixfontein** [comment]
(Try `/file print where contents~"ssh-rsa blaah\\+n"`, that should work)

**Comment by NikolayDachev** [comment]
To clarify something here.
api module use [librouteros](https://librouteros.readthedocs.io/en/latest/query.html )

**Comment by felixfontein** [comment]
BTW, https://wiki.mikrotik.com/wiki/Manual:API says:

> Warning: Regular expressions are not supported in API, so do not try to send query with ~ symbol

So there's no way to support this, since RouterOS itself does not support it.

**Comment by NikolayDachev** [comment]
I will close this one
